{
 "title": "KubeDB / Postgres / Summary",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "db",
    "label": "postgres",
    "query": {
     "query": "query_result(kubedb_postgres_created{namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raft Primary Tracker",
   "type": "timeseries",
   "description": "Track the current Primary for Raft",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_coordinator_raft_primary{namespace=\"$namespace\", pod=~\"$db-.\"}"
    }
   ]
  },
  {
   "title": "Connnections",
   "type": "graph",
   "description": "Postgres connections information in real time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{namespace=\"$namespace\",pod=~\"$db.*\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU Usage by Postgres pods",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "description": "CPU Quote information in details",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Memory Usage by Postgres pods",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$db-.*\",container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\", image!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Disk usage by Postgres pods",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(container_blkio_device_usage_total{namespace=\"$namespace\", pod=~\"$db-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk R/W Info",
     "type": "graph",
     "description": "System Disk Usage Information",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$db-.*\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}-disk-write"
      },
      {
       "expr": "sum(rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$db-.*\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}-disk-read"
      }
     ]
    },
    {
     "title": "IOPS(Reads+Writes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$db.*\"}[5m]) + rate(container_fs_writes_total{container!=\"\" ,namespace=~\"$namespace\", pod=~\"$db.*\"}[5m])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ThroughPut(Read+Write)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$db.*\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\" ,namespace=~\"$namespace\", pod=~\"$db.*\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current Storage IO",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_writes_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_total{container!=\"\",pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\",pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$db.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$db.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}