apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: 11.11-pg-0.6.0-raft-new
spec:
  coordinator:
    image: hremon331046/pg-coordinator:old-with-latest-raft-ver_linux_amd64
  db:
    image: postgres:11.11
  distribution: Official
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.9.0
  initContainer:
    image: kubedb/postgres-init:0.4.0
  podSecurityPolicies:
    databasePolicyName: postgres-db
  securityContext:
    runAsAnyNonRoot: true
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: postgres-backup-11.9
      restoreTask:
        name: postgres-restore-11.9
  version: "11.11"