apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: pg-r35-wofix
  namespace: demo
spec:
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 56790
        resources: {}
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      containerSecurityContext:
        capabilities:
          add:
          - IPC_LOCK
          - SYS_RESOURCE
        privileged: false
        runAsGroup: 999
        runAsUser: 999
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
  replicas: 3
  sslMode: disable
  standbyMode: Hot
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: linode-block-storage
  storageType: Durable
  terminationPolicy: Delete
  version: 11.11-pg-0.6.0-raft-new
